### ISSUE TITLE
The links are still pointing to HackMD

### ISSUE THREAD

**Issue by Cheukting** [numfocus/disc-unconference-2023-projects#27]
@melissawm I realised the 2 links on [our project](https://numfocus.github.io/disc-unconference-2023-projects/en/mentoring_guide_projects.html) - [Checklist for mentee onboarding](https://hackmd.io/@melissawm/onboarding) and [Agenda template for 1-on-1 meetings](https://hackmd.io/@melissawm/11template) is still pointing to a Hack MD file, shall we publish those in the GitBook as well?

**Comment by melissawm** [comment]
Yes, I think we can do that but we didn't have time previously. Do you want to submit a PR? If not, I can take a look probably next week.
